/* 지도와 현재 위치 추천에 사용하는 장소 데이터.
 * 공개 페이지이므로 개인 예약 정보는 넣지 않는다.
 * rating/reviews는 화면에 표시할 Google Maps 평점과 후기 수다.
 */
window.MAP_SPOTS = [
  { name: "시드니 국제공항", query: "Sydney International Airport T1", aliases: ["시드니 국제공항", "시드니 공항"] },
  { name: "실카리 스위트 채스우드", query: "Silkari Suites at Chatswood 88 Archer Street", aliases: ["실카리 스위트 채스우드", "실카리", "채스우드 체크인", "채스우드"] },
  { name: "채스우드역", query: "Chatswood Station NSW", aliases: ["채스우드역"] },
  { name: "거디갈역", query: "Gadigal Station Sydney", aliases: ["거디갈역"] },
  { name: "패디스 마켓", query: "Paddy's Markets Haymarket Sydney", aliases: ["패디스 마켓"] },
  { name: "퀸 빅토리아 빌딩", query: "Queen Victoria Building Sydney", aliases: ["퀸 빅토리아 빌딩", "QVB"] },
  { name: "스트랜드 아케이드", query: "The Strand Arcade Sydney", aliases: ["스트랜드 아케이드", "스트랜드"] },
  { name: "서큘러 키", query: "Circular Quay Sydney", aliases: ["서큘러 키"] },
  { name: "맨리", query: "Manly Wharf Sydney", aliases: ["맨리 F1", "맨리 페리", "맨리"] },
  { name: "시드니현대미술관", query: "Museum of Contemporary Art Australia Sydney", aliases: ["시드니현대미술관", "MCA"] },
  { name: "시드니 오페라하우스", query: "Sydney Opera House", aliases: ["시드니 오페라하우스", "오페라하우스"] },
  { name: "더 록스", query: "The Rocks Sydney", aliases: ["더 록스", "록스"] },
  { name: "히크슨 로드 보호구역", query: "Hickson Road Reserve The Rocks Sydney", aliases: ["히크슨 로드"] },
  { name: "옵저버토리 힐", query: "Observatory Hill Park Sydney", aliases: ["옵저버토리 힐"] },
  { name: "밀슨스 포인트", query: "Milsons Point Sydney", aliases: ["밀슨스 포인트"] },
  { name: "시드니 하버브리지", query: "Sydney Harbour Bridge pedestrian walkway", aliases: ["하버브리지 무료 보행로", "하버브리지 보행로", "하버브리지"] },
  { name: "시드니 피시마켓", query: "Sydney Fish Market Pyrmont", aliases: ["새 시드니 피시마켓", "시드니 피시마켓", "피시마켓"] },
  { name: "쿠지 비치", query: "Coogee Beach Sydney", aliases: ["쿠지 비치", "쿠지"] },
  { name: "고든스 베이", query: "Gordons Bay Sydney", aliases: ["고든스베이", "고든스 베이"] },
  { name: "브론테 비치", query: "Bronte Beach Sydney", aliases: ["브론테 비치", "브론테"] },
  { name: "본다이 비치", query: "Bondi Beach Sydney", aliases: ["본다이 비치", "본다이"] },
  { name: "투가 페이스트리 클로벨리", query: "Tuga Pastries 231 Clovelly Road", aliases: ["투가 페이스트리", "Tuga Pastries"] },
  { name: "Dollar 라일리 스트리트", query: "Dollar Car Rental 95 Riley Street Sydney", aliases: ["Dollar 라일리 스트리트", "95 Riley St", "인수 지점", "RAV4 하이브리드 또는 동급 인수"] },
  { name: "페더데일 야생동물원", query: "Featherdale Sydney Wildlife Park", aliases: ["페더데일 야생동물원", "페더데일"] },
  { name: "시닉 월드", query: "Scenic World Katoomba", aliases: ["시닉 월드", "시닉월드", "레일웨이 하행"] },
  { name: "에코 포인트", query: "Echo Point Lookout Three Sisters Katoomba", aliases: ["에코 포인트", "세 자매봉"] },
  { name: "볼드 힐 전망대", query: "Bald Hill Lookout Stanwell Tops", aliases: ["볼드 힐 전망대", "볼드 힐"] },
  { name: "씨 클리프 브리지", query: "Sea Cliff Bridge NSW", aliases: ["씨 클리프 브리지"] },
  { name: "파크헤이븐", query: "Parkhaven 150-152 Kinghorne Street Nowra", aliases: ["파크헤이븐"] },
  { name: "부데리 국립공원", query: "Booderee National Park Jervis Bay", aliases: ["부데리 국립공원", "부데리"] },
  { name: "머레이스 비치", query: "Murrays Beach Jervis Bay Booderee", aliases: ["머레이스 비치"] },
  { name: "센트럴 틸바", query: "Central Tilba NSW", aliases: ["센트럴 틸바"] },
  { name: "보달라 데어리 셰드", query: "Bodalla Dairy Shed 52 Princes Highway", aliases: ["보달라 데어리 셰드", "보달라 데어리"] },
  { name: "에덴", query: "Eden NSW Australia", aliases: ["에덴 주유", "에덴"] },
  { name: "레이크스 엔트런스", query: "Lakes Entrance Victoria", aliases: ["레이크스 엔트런스"] },
  { name: "시티 가든 모텔", query: "City Gardens Motel 80 Argyle Street Traralgon", aliases: ["시티 가든 모텔", "트랄라곤"] },
  { name: "토키", query: "Torquay Victoria Australia", aliases: ["토키"] },
  { name: "메모리얼 아치", query: "Memorial Arch at Eastern View Great Ocean Road", aliases: ["메모리얼 아치"] },
  { name: "론 해변", query: "Lorne Beach Victoria", aliases: ["론 해변", "론"] },
  { name: "케넷 리버", query: "Kennett River Nature Walk Victoria", aliases: ["케넷 리버"] },
  { name: "더 인터내셔널 모텔", query: "The International Motel 37 Great Ocean Road Apollo Bay", aliases: ["더 인터내셔널 모텔"] },
  { name: "아폴로 베이", query: "Apollo Bay Victoria", aliases: ["아폴로 베이"] },
  { name: "메이츠 레스트", query: "Maits Rest Rainforest Walk", aliases: ["메이츠 레스트"] },
  { name: "12사도", query: "Twelve Apostles Victoria", aliases: ["12사도 바위", "12사도"] },
  { name: "깁슨 스텝스", query: "Gibson Steps Victoria", aliases: ["깁슨 스텝스"] },
  { name: "로크 아드 협곡", query: "Loch Ard Gorge Victoria", aliases: ["로크 아드 협곡", "로크 아드"] },
  { name: "포트 캠벨", query: "Port Campbell Victoria", aliases: ["포트 캠벨"] },
  { name: "질롱", query: "Geelong Victoria", aliases: ["질롱"] },
  { name: "웨리비", query: "Werribee Victoria", aliases: ["웨리비"] },
  { name: "페가수스 아파트호텔", query: "Pegasus Apart'Hotel 206 A'Beckett Street Melbourne", aliases: ["페가수스 아파트호텔", "페가수스", "멜버른 숙소"] },
  { name: "Dollar 프랭클린 스트리트", query: "Dollar Car Rental 8 Franklin Street Melbourne", aliases: ["Shop 3/8 Franklin St", "Dollar 반납"] },
  { name: "조이투어 집결지", query: "RMIT Building 20 325 Russell Street Melbourne", aliases: ["325 Russell Street", "집결지"] },
  { name: "단데농 산맥", query: "Dandenong Ranges National Park Victoria", aliases: ["단데농 산맥"] },
  { name: "퍼핑빌리", query: "Puffing Billy Railway Belgrave", aliases: ["퍼핑빌리"] },
  { name: "사사프라스", query: "Sassafras Victoria", aliases: ["사사프라스"] },
  { name: "마루 동물원", query: "Maru Koala and Animal Park", aliases: ["마루 동물원"] },
  { name: "노비스", query: "The Nobbies Centre Phillip Island", aliases: ["노비스"] },
  { name: "펭귄 퍼레이드", query: "Penguin Parade Phillip Island", aliases: ["펭귄 퍼레이드"] },
  { name: "퀸 빅토리아 마켓", query: "Queen Victoria Market Melbourne", aliases: ["퀸 빅토리아 마켓"] },
  { name: "세븐 시즈 커피 로스터스", query: "Seven Seeds Coffee Roasters Carlton", aliases: ["세븐 시즈 커피 로스터스", "세븐 시즈"] },
  { name: "오퍼레이터 25", query: "Operator 25 Melbourne", aliases: ["오퍼레이터 25"] },
  { name: "멜버른 대학교 올드 쿼드", query: "Old Quadrangle University of Melbourne", aliases: ["멜버른 대학교 올드 쿼드", "멜버른 대학교"] },
  { name: "칼턴 가든", query: "Carlton Gardens Melbourne", aliases: ["칼턴 가든"] },
  { name: "로열 엑시비션 빌딩", query: "Royal Exhibition Building Melbourne", aliases: ["로열 엑시비션 빌딩"] },
  { name: "빅토리아 주립도서관", query: "State Library Victoria", aliases: ["주립도서관 돔", "주립도서관"] },
  { name: "하드웨어 레인", query: "Hardware Lane Melbourne", aliases: ["하드웨어 레인"] },
  { name: "디그레이브스 스트리트", query: "Degraves Street Melbourne", aliases: ["디그레이브스"] },
  { name: "센터 플레이스", query: "Centre Place Melbourne", aliases: ["센터 플레이스"] },
  { name: "호시어 레인", query: "Hosier Lane Melbourne", aliases: ["호시어 레인"] },
  { name: "블록 아케이드", query: "Block Arcade Melbourne", aliases: ["블록 아케이드"] },
  { name: "로열 아케이드", query: "Royal Arcade Melbourne", aliases: ["로열 아케이드"] },
  { name: "플린더스 스트리트역", query: "Flinders Street Station Melbourne", aliases: ["플린더스역", "플린더스 스트리트역"] },
  { name: "슈라인 오브 리멤버런스", query: "Shrine of Remembrance Melbourne", aliases: ["슈라인 오브 리멤버런스", "슈라인"] },
  { name: "야라강", query: "Southbank Promenade Melbourne", aliases: ["야라강"] },
  { name: "멜버른 CBD", query: "Melbourne Central Business District", aliases: ["멜버른 CBD", "CBD 쇼핑"] },
  { name: "서던 크로스역", query: "Southern Cross Station Melbourne", aliases: ["서던 크로스"] },
  { name: "룬 크루아상 론즈데일", query: "Lune Croissanterie Melbourne CBD", aliases: ["룬 크루아상", "룬 론즈데일"] },
  { name: "하이어 그라운드", query: "Higher Ground Melbourne", aliases: ["하이어 그라운드"] },
  { name: "티포 00", query: "Tipo 00 Melbourne", aliases: ["티포 00"] },
  { name: "룰루레몬 콜링우드 팩토리 아울렛", query: "lululemon Collingwood Factory Outlet 131-143 Smith Street", aliases: ["룰루레몬 콜링우드 팩토리 아울렛", "룰루레몬 아울렛"] },
  { name: "DFO 사우스워프", query: "DFO South Wharf Melbourne", aliases: ["DFO 사우스워프", "사우스워프"] },
  { name: "뱅팝 사우스워프", query: "BangPop South Wharf Melbourne", aliases: ["뱅팝 사우스워프", "뱅팝"] },
  { name: "브라이턴 배싱 박스", query: "Brighton Bathing Boxes Victoria", aliases: ["브라이턴 배싱 박스", "브라이턴 비치"] },
  { name: "멜버른 공항", query: "Melbourne Airport International Terminal", aliases: ["멜버른 공항"] },
  { name: "떤선녓 국제공항", query: "Tan Son Nhat International Airport T2", aliases: ["떤선녓공항", "떤선녓 국제공항", "그랩 → 공항", "호치민 출발"] },
  { name: "쩌런", query: "Cho Lon Ho Chi Minh City", aliases: ["쩌런"] },
  { name: "틴하우 사원", query: "Thien Hau Temple Ho Chi Minh City", aliases: ["틴하우사원", "틴하우 사원"] },
  { name: "빈떠이 시장", query: "Binh Tay Market Ho Chi Minh City", aliases: ["빈떠이시장", "빈떠이 시장"] },
  { name: "벤탄 시장", query: "Ben Thanh Market Ho Chi Minh City", aliases: ["벤탄 나이트마켓", "벤탄시장", "벤탄 시장"] },
  { name: "사이공스퀘어", query: "Saigon Square Ho Chi Minh City", aliases: ["사이공스퀘어", "사이공 스퀘어"] },
  { name: "사이공 중앙우체국", query: "Saigon Central Post Office", aliases: ["중앙우체국"] },
  { name: "노트르담 대성당", query: "Notre Dame Cathedral of Saigon", aliases: ["노트르담 성당", "노트르담"] },
  { name: "독립궁", query: "Independence Palace Ho Chi Minh City", aliases: ["독립궁"] },
  { name: "응우옌후에 거리", query: "Nguyen Hue Walking Street", aliases: ["응우옌후에 거리"] },
  { name: "카페 아파트먼트", query: "The Cafe Apartment 42 Nguyen Hue", aliases: ["카페 아파트먼트"] },
  { name: "사이공강변", query: "Bach Dang Wharf Park Ho Chi Minh City", aliases: ["사이공강변", "Bach Dang"] },
  { name: "비텍스코 스카이덱", query: "Saigon Skydeck Bitexco", aliases: ["비텍스코 스카이덱", "비텍스코"] },
  { name: "부이비엔 거리", query: "Bui Vien Walking Street", aliases: ["부이비엔 거리"] },
  { name: "인천국제공항", query: "Incheon International Airport", aliases: ["인천국제공항"] },
];

window.NEARBY_PLACES = [
  { name: "검프션 바이 커피 알케미", kind: "커피", note: "플랫화이트와 싱글 오리진 커피", lat: -33.8693690, lon: 151.2075243, rating: 4.3, reviews: 1375, query: "Gumption by Coffee Alchemy Sydney" },
  { name: "마막 채스우드", kind: "식사", note: "로티 차나이와 나시 르막", lat: -33.7966157, lon: 151.1805501, rating: 4.2, reviews: 1898, query: "Mamak Chatswood Sydney" },
  { name: "마막 헤이마켓", kind: "식사", note: "로티와 미고렝으로 유명한 말레이시아 식당", lat: -33.8777789, lon: 151.2041972, rating: 4.3, reviews: 6108, query: "Mamak Haymarket Sydney" },
  { name: "아니타 젤라토 바랑가루", kind: "디저트", note: "항구 산책 중 들르기 좋은 젤라토", lat: -33.8611374, lon: 151.2126457, rating: 4.6, reviews: 457, query: "Anita Gelato Barangaroo Sydney" },
  { name: "패디스 마켓", kind: "시장", note: "간식과 기념품을 함께 볼 수 있는 시장", lat: -33.8800089, lon: 151.2035622, reviews: 23768, query: "Paddy's Markets Haymarket Sydney" },
  { name: "퀸 빅토리아 빌딩", kind: "명소", note: "쇼핑보다 건축과 내부 장식을 보기 좋은 곳", lat: -33.8717161, lon: 151.2067008, reviews: 19004, query: "Queen Victoria Building Sydney" },
  { name: "스트랜드 아케이드", kind: "명소", note: "빅토리아 시대 아케이드와 상점", lat: -33.8693593, lon: 151.2075288, reviews: 6388, query: "The Strand Arcade Sydney" },
  { name: "시드니 오페라하우스", kind: "명소", note: "서큘러 키에서 외관과 항구 사진을 보기 좋은 곳", lat: -33.8567844, lon: 151.2152967, reviews: 96000, query: "Sydney Opera House" },
  { name: "더 록스", kind: "명소", note: "오래된 골목과 항구 풍경을 함께 볼 수 있는 지역", lat: -33.8590620, lon: 151.2080421, reviews: 25000, query: "The Rocks Sydney" },
  { name: "옵저버토리 힐", kind: "전망", note: "하버브리지와 항구를 무료로 볼 수 있는 전망대", lat: -33.8594047, lon: 151.2048859, rating: 4.7, reviews: 14205, query: "Observatory Hill Park Sydney" },
  { name: "시드니 피시마켓", kind: "시장", note: "굴과 생선 요리를 골라 먹기 좋은 시장", lat: -33.8713786, lon: 151.1949048, rating: 4.2, reviews: 87904, query: "Sydney Fish Market Pyrmont" },
  { name: "본다이 아이스버그스 클럽", kind: "식사", note: "바다 전망과 피시앤칩스를 함께 즐기는 곳", lat: -33.8950891, lon: 151.2743049, rating: 4.4, reviews: 9073, query: "Bondi Icebergs Club Sydney" },
  { name: "본다이 로드 시푸드", kind: "식사", note: "피시앤칩스와 해산물 포장", lat: -33.8947367, lon: 151.2682556, rating: 4.5, reviews: 592, query: "Bondi Road Seafoods Sydney" },
  { name: "빌스 본다이", kind: "브런치", note: "리코타 핫케이크와 스크램블에그", lat: -33.8898493, lon: 151.2720552, rating: 4.2, reviews: 2449, query: "bills Bondi Sydney" },
  { name: "A.P 베이커리 서리힐스", kind: "베이커리", note: "사워도우와 페이스트리", lat: -33.8793612, lon: 151.2110565, rating: 4.1, reviews: 2979, query: "A.P House Bakery Surry Hills Sydney" },
  { name: "싱글오", kind: "커피", note: "시드니 스페셜티 커피로 자주 소개되는 곳", lat: -33.8810973, lon: 151.2096465, rating: 4.5, reviews: 4913, query: "Single O Surry Hills Sydney" },
  { name: "투가 페이스트리 클로벨리", kind: "베이커리", note: "해안 산책에서 짧게 우회해 먹는 포르투갈식 에그타르트", lat: -33.9114563, lon: 151.2547203, query: "Tuga Pastries 231 Clovelly Road" },
  { name: "페더데일 야생동물원", kind: "명소", note: "코알라와 캥거루를 가까이에서 볼 수 있는 동물원", lat: -33.7658201, lon: 150.8842415, reviews: 25000, query: "Featherdale Sydney Wildlife Park" },
  { name: "시닉 월드", kind: "명소", note: "레일웨이·워크웨이·케이블웨이·스카이웨이", lat: -33.7288041, lon: 150.3012037, reviews: 23658, query: "Scenic World Katoomba" },
  { name: "옐로우 델리", kind: "식사", note: "샌드위치와 수프를 먹기 좋은 카툼바 식당", lat: -33.7174189, lon: 150.3111229, rating: 4.5, reviews: 3107, query: "The Yellow Deli Katoomba" },
  { name: "블랙 코카투 베이커리", kind: "베이커리", note: "사워도우와 페이스트리", lat: -33.7160336, lon: 150.3111220, rating: 4.6, reviews: 359, query: "Black Cockatoo Bakery Katoomba" },
  { name: "카시오페이아 커피", kind: "커피", note: "카툼바의 스페셜티 커피", lat: -33.7194013, lon: 150.3119687, rating: 4.6, reviews: 629, query: "Cassiopeia Coffee Katoomba" },
  { name: "하이퍼 하이퍼 커피", kind: "커피", note: "나우라 시내에서 평이 좋은 로스터리", lat: -34.8726557, lon: 150.6038127, rating: 4.5, reviews: 786, query: "Hyper Hyper Coffee Nowra" },
  { name: "머레이스 비치", kind: "명소", note: "부데리 국립공원의 잔잔한 백사장", lat: -35.1254217, lon: 150.7581123, query: "Murrays Beach Jervis Bay Booderee" },
  { name: "틸바 티포트 카페", kind: "카페", note: "센트럴 틸바 산책 중 차와 간식을 먹기 좋은 곳", lat: -36.3123324, lon: 150.0749997, rating: 4.6, reviews: 300, query: "The Tilba Teapot Cafe Central Tilba" },
  { name: "틸바 데어리", kind: "디저트", note: "현지 치즈와 아이스크림", lat: -36.3110669, lon: 150.0750866, rating: 4.5, reviews: 671, query: "Tilba Dairy Central Tilba" },
  { name: "보달라 데어리 셰드", kind: "디저트", note: "프린시스 하이웨이 바로 옆에서 먹는 현지 아이스크림과 치즈", lat: -36.0866198, lon: 150.0493450, query: "Bodalla Dairy Shed 52 Princes Highway" },
  { name: "훅트 온 시푸드", kind: "식사", note: "에덴에서 생선과 감자튀김을 포장하기 좋은 곳", lat: -37.0721544, lon: 149.9105195, rating: 4.2, reviews: 359, query: "Hooked On Seafood Eden NSW" },
  { name: "펑키 몽키 카페", kind: "카페", note: "레이크스 엔트런스의 브런치와 커피", lat: -37.8782827, lon: 147.9941607, rating: 4.4, reviews: 1101, query: "Funkey Monkey Cafe Lakes Entrance" },
  { name: "레이크스 엔트런스 풋브리지", kind: "명소", note: "짧게 걷기 좋은 호숫가 보행교", lat: -37.8807409, lon: 147.9938767, reviews: 1205, query: "Cunninghame Arm Foot Bridge Lakes Entrance" },
  { name: "푸드 코 온 프랭클린", kind: "카페", note: "트랄라곤에서 아침과 커피를 빠르게 해결하기 좋은 곳", lat: -38.1902778, lon: 146.5386111, rating: 4.6, reviews: 915, query: "Food Co On Franklin Traralgon" },
  { name: "리틀 프린스 이팅 하우스", kind: "식사", note: "트랄라곤 시내의 브런치와 저녁 식사", lat: -38.1970920, lon: 146.5372460, rating: 4.5, reviews: 253, query: "Little Prince Eating House Traralgon" },
  { name: "리틀 띵스 빅 띵스", kind: "브런치", note: "토키의 브런치와 스페셜티 커피", lat: -38.3323625, lon: 144.3239589, rating: 4.7, reviews: 142, query: "Little Things Big Things Cafe Torquay" },
  { name: "폰드 카페", kind: "카페", note: "토키 중심가에서 가볍게 먹기 좋은 카페", lat: -38.3322007, lon: 144.3261103, rating: 4.3, reviews: 744, query: "Pond Cafe Torquay" },
  { name: "피쇼스 토키", kind: "식사", note: "생선 요리와 해산물", lat: -38.3328169, lon: 144.3258138, rating: 4.5, reviews: 1758, query: "Fishos Torquay" },
  { name: "메모리얼 아치", kind: "명소", note: "그레이트오션로드 표지와 기념사진을 남기는 곳", lat: -38.4719227, lon: 144.0445336, reviews: 5355, query: "Memorial Arch at Eastern View" },
  { name: "스윙브리지 카페", kind: "카페", note: "강과 해변을 함께 볼 수 있는 론의 카페", lat: -38.5338851, lon: 143.9779986, rating: 4.4, reviews: 644, query: "Swingbridge Cafe Lorne" },
  { name: "더 보틀 오브 밀크", kind: "식사", note: "버거와 감자튀김", lat: -38.5380789, lon: 143.9750113, rating: 4.2, reviews: 1362, query: "The Bottle of Milk Lorne" },
  { name: "입소스", kind: "식사", note: "그리스식 해산물과 그릴 요리", lat: -38.5379587, lon: 143.9749967, rating: 4.6, reviews: 845, query: "Ipsos Restaurant Lorne" },
  { name: "케넷 리버 네이처 워크", kind: "명소", note: "야생 코알라를 찾아보는 짧은 산책로", lat: -38.6666115, lon: 143.8617647, reviews: 308, query: "Kennett River Nature Walk" },
  { name: "아폴로 베이 베이커리", kind: "베이커리", note: "이 지역에서 유명한 가리비 파이", lat: -38.7559624, lon: 143.6691589, rating: 4.4, reviews: 1857, query: "Apollo Bay Bakery" },
  { name: "아폴로 베이 피셔맨스 코옵", kind: "식사", note: "가리비와 피시앤칩스를 먹기 좋은 어시장", lat: -38.7595927, lon: 143.6748481, rating: 4.3, reviews: 3200, query: "Apollo Bay Fishermen's Co-op" },
  { name: "12사도", kind: "명소", note: "그레이트오션로드의 대표 해안 전망대", lat: -38.6621015, lon: 143.1050917, reviews: 59000, query: "Twelve Apostles Victoria" },
  { name: "깁슨 스텝스", kind: "명소", note: "절벽 아래 해변으로 내려가는 계단", lat: -38.6686946, lon: 143.1120188, reviews: 5700, query: "Gibson Steps Victoria" },
  { name: "로크 아드 협곡", kind: "명소", note: "절벽과 협곡을 가까이에서 볼 수 있는 전망 구간", lat: -38.6465896, lon: 143.0705094, reviews: 7252, query: "Loch Ard Gorge Victoria" },
  { name: "그래스루츠 델리 카페", kind: "카페", note: "포트 캠벨에서 파이와 샌드위치를 먹기 좋은 곳", lat: -38.6199540, lon: 142.9951410, rating: 4.5, reviews: 1143, query: "Grassroots Deli Cafe Port Campbell" },
  { name: "포리지 온 더 포쇼어", kind: "브런치", note: "포트 캠벨 해변 앞 브런치 카페", lat: -38.6197460, lon: 142.9937615, rating: 4.3, reviews: 468, query: "Forage on the Foreshore Port Campbell" },
  { name: "12 록스 비치 바", kind: "식사", note: "버거와 피시앤칩스", lat: -38.6200345, lon: 142.9941296, rating: 4.2, reviews: 2245, query: "12 Rocks Beach Bar Cafe Port Campbell" },
  { name: "퍼핑빌리", kind: "명소", note: "단데농 산맥을 달리는 증기기관차", lat: -37.9077353, lon: 145.3566269, reviews: 10272, query: "Puffing Billy Railway Belgrave" },
  { name: "미스 마플스 티룸", kind: "카페", note: "사사프라스의 스콘과 파이", lat: -37.8634805, lon: 145.3535810, rating: 4.4, reviews: 3052, query: "Miss Marple's Tearoom Sassafras" },
  { name: "사사프라스 카페", kind: "카페", note: "투어 중 빠르게 먹기 좋은 브런치와 커피", lat: -37.8622220, lon: 145.3538606, rating: 4.4, reviews: 749, query: "Sassafras Cafe Victoria" },
  { name: "마루 동물원", kind: "명소", note: "코알라와 호주 야생동물을 볼 수 있는 공원", lat: -38.4178133, lon: 145.5205860, reviews: 20349, query: "Maru Koala and Animal Park" },
  { name: "노비스 센터", kind: "명소", note: "필립아일랜드 해안 절벽과 보드워크", lat: -38.5174032, lon: 145.1179750, reviews: 13000, query: "The Nobbies Centre Phillip Island" },
  { name: "펭귄 퍼레이드", kind: "명소", note: "해 질 무렵 돌아오는 리틀펭귄 관람", lat: -38.5066164, lon: 145.1497290, reviews: 12724, query: "Penguin Parade Phillip Island" },
  { name: "마켓 레인 커피", kind: "커피", note: "퀸 빅토리아 마켓에서 마시기 좋은 플랫화이트", lat: -37.8075798, lon: 144.9567850, rating: 4.6, reviews: 1879, query: "Market Lane Coffee Queen Victoria Market Melbourne" },
  { name: "세븐 시즈 커피 로스터스", kind: "커피·브런치", note: "퀸 빅토리아 마켓과 멜버른 대학교 사이의 로스터리 카페", lat: -37.8028349, lon: 144.9590354, query: "Seven Seeds Coffee Roasters Carlton" },
  { name: "오퍼레이터 25", kind: "커피·브런치", note: "페가수스 근처의 아시안 브런치와 스페셜티 커피", lat: -37.8107145, lon: 144.9571233, query: "Operator 25 Melbourne" },
  { name: "보렉스", kind: "간식", note: "퀸 빅토리아 마켓의 치즈·시금치 보렉", lat: -37.8070590, lon: 144.9593071, rating: 4.1, reviews: 169, query: "Boreks Queen Victoria Market Melbourne" },
  { name: "아메리칸 도넛 키친", kind: "디저트", note: "마켓에서 바로 튀겨 주는 잼 도넛", lat: -37.8073416, lon: 144.9581179, rating: 4.5, reviews: 1161, query: "American Doughnut Kitchen Melbourne" },
  { name: "빅토리아 주립도서관", kind: "명소", note: "라 트로브 돔 열람실을 무료로 볼 수 있는 곳", lat: -37.8097255, lon: 144.9654504, reviews: 4827, query: "State Library Victoria" },
  { name: "로열 엑시비션 빌딩", kind: "명소", note: "칼턴 가든과 함께 외관을 보기 좋은 건축물", lat: -37.8046891, lon: 144.9716502, reviews: 6900, query: "Royal Exhibition Building Melbourne" },
  { name: "호시어 레인", kind: "명소", note: "멜버른의 대표적인 그래피티 골목", lat: -37.8165272, lon: 144.9691574, reviews: 963, query: "Hosier Lane Melbourne" },
  { name: "블록 아케이드", kind: "명소", note: "모자이크 바닥과 유리 지붕이 남아 있는 아케이드", lat: -37.8155205, lon: 144.9645141, reviews: 3419, query: "Block Arcade Melbourne" },
  { name: "슈라인 오브 리멤버런스", kind: "명소", note: "멜버른 도심을 내려다볼 수 있는 기념관", lat: -37.8305164, lon: 144.9734319, reviews: 9037, query: "Shrine of Remembrance Melbourne" },
  { name: "패트리샤 커피", kind: "커피", note: "서서 마시는 멜버른 대표 스페셜티 커피", lat: -37.8146934, lon: 144.9582383, rating: 4.8, reviews: 5044, query: "Patricia Coffee Brewers Melbourne" },
  { name: "친친 멜버른", kind: "식사", note: "활기찬 분위기의 동남아 요리", lat: -37.8156149, lon: 144.9703757, rating: 4.2, reviews: 8453, query: "Chin Chin Melbourne" },
  { name: "룬 크루아상", kind: "베이커리", note: "클래식과 아몬드 크루아상", lat: -37.8156295, lon: 144.9692426, rating: 4.4, reviews: 9200, query: "Lune Croissanterie Melbourne CBD Russell Street" },
  { name: "하이어 그라운드", kind: "브런치", note: "높은 천장의 공간으로도 유명한 브런치 카페", lat: -37.8157491, lon: 144.9530438, rating: 4.1, reviews: 10328, query: "Higher Ground Melbourne" },
  { name: "티포 00", kind: "예약 식당", note: "파스타와 티포미수로 유명한 이탈리아 식당", lat: -37.8135522, lon: 144.9619835, rating: 4.5, reviews: 5976, query: "Tipo 00 Melbourne" },
  { name: "룰루레몬 콜링우드 팩토리 아울렛", kind: "쇼핑", note: "17:30에 닫는 룰루레몬 공식 팩토리 아울렛", lat: -37.8049454, lon: 144.9830343, query: "lululemon Collingwood Factory Outlet 131-143 Smith Street" },
  { name: "DFO 사우스워프", kind: "쇼핑", note: "금요일 21:00까지 운영하는 대형 아울렛·룰루레몬은 없음", lat: -37.8251278, lon: 144.9491461, query: "DFO South Wharf Melbourne" },
  { name: "뱅팝 사우스워프", kind: "식사", note: "DFO 쇼핑 뒤 들르기 좋은 야라강변 태국식 호커 레스토랑", lat: -37.8242022, lon: 144.9514921, query: "BangPop South Wharf Melbourne" },
  { name: "브라더 바바 부단", kind: "커피", note: "멜버른 CBD에서 플랫화이트로 유명한 카페", lat: -37.8135410, lon: 144.9620988, rating: 4.5, reviews: 3405, query: "Brother Baba Budan Melbourne" },
  { name: "하드웨어 소시에테", kind: "브런치", note: "프렌치 스타일 브런치와 커피", lat: -37.8136276, lon: 144.9630576, rating: 4.4, reviews: 7631, query: "The Hardware Societe Melbourne" },
  { name: "브라이턴 배싱 박스", kind: "명소", note: "알록달록한 해변 오두막을 볼 수 있는 포토 스팟", lat: -37.9128827, lon: 144.9915515, reviews: 32491, query: "Brighton Bathing Boxes Victoria" },
  { name: "팬트리 브라이턴", kind: "브런치", note: "브라이턴에서 오래 운영한 브런치 카페", lat: -37.9124489, lon: 144.9929399, rating: 4.1, reviews: 711, query: "The Pantry Brighton Victoria" },
  { name: "반미 후인호아", kind: "식사", note: "속이 꽉 찬 반미로 유명한 곳", lat: 10.7715226, lon: 106.6923968, rating: 4.1, reviews: 7658, query: "Banh Mi Huynh Hoa Ho Chi Minh City" },
  { name: "퍼 호아 파스퇴르", kind: "식사", note: "진한 국물의 호찌민식 쌀국수", lat: 10.7866905, lon: 106.6892627, rating: 4.2, reviews: 6101, query: "Pho Hoa Pasteur Ho Chi Minh City" },
  { name: "벱메인", kind: "식사", note: "벤탄시장 근처에서 먹기 좋은 베트남 가정식", lat: 10.7738567, lon: 106.6980798, rating: 4.7, reviews: 21680, query: "Bep Me In Le Thanh Ton Ho Chi Minh City" },
  { name: "카페 아파트먼트", kind: "카페·명소", note: "한 건물에 여러 카페가 모여 있는 응우옌후에 명소", lat: 10.7740857, lon: 106.7041064, rating: 4.4, reviews: 5627, query: "The Cafe Apartment 42 Nguyen Hue Ho Chi Minh City" },
];

/* 일정에 넣지는 않았지만 같은 날 동선에서 고를 만한 유명 장소.
 * 장소명은 Google Maps 검색 결과(장소 상세)로 연결한다.
 */
window.EXTRA_PLACES_BY_DAY = {
  1: [
    { name: "검프션 바이 커피 알케미", query: "Gumption by Coffee Alchemy Sydney", note: "QVB·스트랜드 아케이드 근처 플랫화이트 후보" },
    { name: "마막 헤이마켓", query: "Mamak Haymarket Sydney", note: "호텔 복귀 전후로 먹기 좋은 로티 차나이·나시 르막" },
    { name: "아니타 젤라토 바랑가루", query: "Anita Gelato Barangaroo Sydney", note: "더 록스·바랑가루 산책 중 짧게 넣기 좋은 디저트" },
    { name: "바랑가루 리저브", query: "Barangaroo Reserve Sydney", note: "항구 산책과 하버브리지 사진을 함께 보기 좋은 무료 공원" },
    { name: "옵저버토리 힐", query: "Observatory Hill Park Sydney", note: "더 록스에서 걸어갈 수 있는 하버브리지 노을 전망대" },
    { name: "도스 포인트 리저브", query: "Dawes Point Reserve Sydney", note: "하버브리지 바로 아래에서 오페라하우스를 마주 보는 포토 스팟" },
  ],
  2: [
    { name: "싱글오", query: "Single O Surry Hills Sydney", note: "차 받기 전 시내 쪽에서 들르기 좋은 스페셜티 커피" },
    { name: "A.P 베이커리 서리힐스", query: "A.P House Bakery Surry Hills Sydney", note: "사워도우·페이스트리로 많이 찾는 베이커리" },
    { name: "본다이 아이스버그스 클럽", query: "Bondi Icebergs Club Sydney", note: "본다이 바다 전망 보면서 가볍게 먹기 좋은 곳" },
    { name: "본다이 로드 시푸드", query: "Bondi Road Seafoods Sydney", note: "해안 산책 뒤 피시앤칩스 포장 후보" },
    { name: "클로벨리 비치", query: "Clovelly Beach Sydney", note: "쿠지~본다이 해안길 중간의 좁고 잔잔한 만" },
    { name: "브론테 배스", query: "Bronte Baths Sydney", note: "브론테 비치 남쪽 끝의 무료 오션풀" },
    { name: "타마라마 비치", query: "Tamarama Beach Sydney", note: "본다이 직전 절벽 사이에 자리한 작은 해변" },
  ],
  3: [
    { name: "옐로우 델리", query: "The Yellow Deli Katoomba", note: "카툼바에서 샌드위치·수프 먹기 좋은 대표 식당" },
    { name: "블랙 코카투 베이커리", query: "Black Cockatoo Bakery Katoomba", note: "블루마운틴 동선 중 페이스트리·커피 보급지" },
    { name: "카시오페이아 커피", query: "Cassiopeia Coffee Katoomba", note: "카툼바에서 커피만 빠르게 마실 때 후보" },
    { name: "웬트워스 폭포 전망대", query: "Wentworth Falls Lookout NSW", note: "시간이 남을 때 에코 포인트 대신 고를 만한 블루마운틴 전망대" },
    { name: "케이힐스 룩아웃", query: "Cahill's Lookout Katoomba", note: "세 자매봉보다 한적한 편인 카툼바 서쪽 전망대" },
    { name: "키아마 블로우홀", query: "Kiama Blowhole NSW", note: "파도가 좋은 날만 볼 만한 분수형 바위 구멍·당일 지연 시 제외" },
  ],
  4: [
    { name: "하이퍼 하이퍼 커피", query: "Hyper Hyper Coffee Nowra", note: "나우라 출발 전 커피가 필요하면 가까운 후보" },
    { name: "틸바 티포트 카페", query: "The Tilba Teapot Cafe Central Tilba", note: "센트럴 틸바를 들르면 차와 간식으로 묶기 좋음" },
    { name: "보달라 데어리 셰드", query: "Bodalla Dairy Shed 52 Princes Highway", note: "남하 중 아이스크림·치즈로 짧게 쉬기 좋은 곳" },
    { name: "푸드 코 온 프랭클린", query: "Food Co On Franklin Traralgon", note: "트랄라곤 도착 후 또는 다음날 아침 커피 후보" },
    { name: "그린 패치", query: "Green Patch Booderee National Park", note: "부데리 안에서 해변과 야생 캥거루를 함께 볼 수 있는 구역" },
    { name: "하이엄스 비치", query: "Hyams Beach Jervis Bay", note: "밝은 백사장으로 유명하지만 머레이스 비치와 방향이 달라 여유 있을 때만" },
    { name: "레이크스 엔트런스 풋브리지", query: "Cunninghame Arm Foot Bridge Lakes Entrance", note: "장거리 운전 중 호숫가를 10분 정도 걷기 좋은 보행교" },
  ],
  5: [
    { name: "리틀 띵스 빅 띵스", query: "Little Things Big Things Cafe Torquay", note: "토키에서 브런치와 커피를 같이 해결하기 좋은 카페" },
    { name: "피쇼스 토키", query: "Fishos Torquay", note: "그레이트오션로드 진입 전 해산물 식사 후보" },
    { name: "스윙브리지 카페", query: "Swingbridge Cafe Lorne", note: "론 해변·강가를 같이 보며 쉬기 좋은 카페" },
    { name: "아폴로 베이 베이커리", query: "Apollo Bay Bakery", note: "아폴로베이에서 유명한 가리비 파이 후보" },
    { name: "벨스 비치", query: "Bells Beach Torquay Victoria", note: "토키 근처의 세계적인 서핑 해변·일정이 빠를 때만" },
    { name: "테디스 룩아웃", query: "Teddy's Lookout Lorne Victoria", note: "론과 그레이트오션로드 굽이길을 내려다보는 짧은 전망 정차" },
  ],
  6: [
    { name: "아폴로 베이 피셔맨스 코옵", query: "Apollo Bay Fishermen's Co-op", note: "아침 동선이 맞으면 해산물·가리비 쪽으로 유명한 곳" },
    { name: "그래스루츠 델리 카페", query: "Grassroots Deli Cafe Port Campbell", note: "포트 캠벨에서 파이·샌드위치로 점심 보급" },
    { name: "포리지 온 더 포쇼어", query: "Forage on the Foreshore Port Campbell", note: "포트 캠벨 해변 앞 브런치 카페" },
    { name: "12 록스 비치 바", query: "12 Rocks Beach Bar Cafe Port Campbell", note: "12사도 뒤 피시앤칩스·버거 후보" },
    { name: "더 그로토", query: "The Grotto Great Ocean Road Victoria", note: "바위 창 사이로 바다를 보는 포트캠벨 서쪽 전망지·반납 여유가 있을 때만" },
    { name: "런던 아치", query: "London Arch Great Ocean Road Victoria", note: "붕괴 뒤 두 조각으로 남은 해식 아치·더 그로토와 둘 중 하나만" },
  ],
  7: [
    { name: "미스 마플스 티룸", query: "Miss Marple's Tearoom Sassafras", note: "단데농 투어 중 스콘·차로 자주 언급되는 티룸" },
    { name: "사사프라스 카페", query: "Sassafras Cafe Victoria", note: "투어 중 짧게 브런치와 커피를 해결하기 좋은 곳" },
  ],
  8: [
    { name: "마켓 레인 커피", query: "Market Lane Coffee Queen Victoria Market Melbourne", note: "퀸 빅토리아 마켓에서 플랫화이트 마시기 좋은 곳" },
    { name: "아메리칸 도넛 키친", query: "American Doughnut Kitchen Melbourne", note: "마켓 먹방 코스에서 빠지기 아쉬운 잼 도넛" },
    { name: "오퍼레이터 25", query: "Operator 25 Melbourne", note: "페가수스 근처 브런치·커피 후보" },
    { name: "세븐 시즈 커피 로스터스", query: "Seven Seeds Coffee Roasters Carlton", note: "멜버른대·칼턴 쪽으로 걸을 때 넣기 좋은 로스터리" },
    { name: "세인트 폴 대성당", query: "St Paul's Cathedral Melbourne", note: "플린더스 스트리트역 맞은편의 고딕 리바이벌 건축" },
    { name: "페더레이션 스퀘어", query: "Federation Square Melbourne", note: "플린더스역·호시어 레인 사이에서 잠깐 보기 좋은 도심 광장" },
    { name: "AC/DC 레인", query: "ACDC Lane Melbourne", note: "호시어 레인과 함께 묶기 좋은 음악 테마 그래피티 골목" },
    { name: "피츠로이 가든", query: "Fitzroy Gardens Melbourne", note: "칼턴·CBD 동선이 빨리 끝났을 때 걷기 좋은 정원" },
  ],
  9: [
    { name: "티포 00", query: "Tipo 00 Melbourne", note: "예약해둔 파스타 맛집·티포미수까지 체크" },
    { name: "룬 크루아상", query: "Lune Croissanterie Melbourne CBD Russell Street", note: "오전 동선이 맞으면 크루아상 픽업 후보" },
    { name: "하이어 그라운드", query: "Higher Ground Melbourne", note: "공간감으로도 유명한 멜버른 브런치 카페" },
    { name: "브라더 바바 부단", query: "Brother Baba Budan Melbourne", note: "CBD 플랫화이트 후보·짧게 들르기 좋음" },
    { name: "뱅팝 사우스워프", query: "BangPop South Wharf Melbourne", note: "DFO 사우스워프 뒤 야라강변 식사 후보" },
    { name: "사우스 멜버른 마켓", query: "South Melbourne Market", note: "브라이턴 복귀 뒤 시간이 남을 때 들를 수 있는 식료품·먹거리 시장" },
    { name: "알렉산드라 가든", query: "Alexandra Gardens Melbourne", note: "야라강 산책을 조금 더 이어가고 싶을 때 고르는 무료 정원" },
  ],
  10: [
    { name: "반미 후인호아", query: "Banh Mi Huynh Hoa Ho Chi Minh City", note: "호치민 반미로 자주 언급되는 곳·대기 감안" },
    { name: "퍼 호아 파스퇴르", query: "Pho Hoa Pasteur Ho Chi Minh City", note: "쌀국수로 한 끼를 빨리 해결하기 좋은 후보" },
    { name: "벱메인", query: "Bep Me In Le Thanh Ton Ho Chi Minh City", note: "벤탄시장 근처 베트남 가정식 후보" },
    { name: "카페 아파트먼트", query: "The Cafe Apartment 42 Nguyen Hue Ho Chi Minh City", note: "응우옌후에 거리에서 카페와 건물 구경을 함께" },
  ],
};
